### ISSUE TITLE
Option to use `npm ci`

### ISSUE THREAD

**Issue by jonyeezs** [jonathantneal/post-npm-install#2]
npm v5.7 introduced `npm ci` - https://docs.npmjs.com/cli/ci.html

I reckon this will be a good fit for this project.

Reason:
1. When someone upgrades/downgrades/removes/adds a pkg it will update the lock file.
2. npm ci will not update any files (ie the lock file)
3. Keeping the state as declared by the previous commit that actually did the package.json update.
4. It'll be quicker to install
5. albeit rm-s node_modules and reinstall, this will give you a good state as expected by the commit that did the package.json change.

**Comment by jonathantneal** [comment]
We can probably do this. It will involve checking for a change to `package-lock.json` before checking for a change to `package.json`.

> The project must have an existing `package-lock.json` or `npm-shrinkwrap.json`.

I’m tentatively open to this. Thanks for bringing it up.

**Comment by jonyeezs** [comment]
Hi @jonathantneal would a pkg be publish for the changes?

**Comment by felixjb** [comment]
How do I use this option?

**Comment by jonyeezs** [comment]
Hi @felixjb 

Try `post-npm-install ci`

There's a PR #6 to add it to README

**Comment by felixjb** [comment]
Thank you!
