### ISSUE TITLE
Latest commit change has not been publish.

### ISSUE THREAD

**Issue by jonyeezs** [jonathantneal/post-npm-install#4]
Hi @jonathantneal. Still waiting for the latest commit to be publish.

Anything i can help with the hold-up?

**Comment by jonathantneal** [comment]
Thank you for diligently reminding me to update this project.

A Node 6+ compatible version has been published as v1.1.0.
A Node 8+ compatible version has been published as v2.0.0.

Both versions include the `npm ci` functionality.
